### ISSUE TITLE
xchina.co issue

### ISSUE THREAD

**Issue by DayatXD** [LARASPY/xhua#2]
the **全部视频** button on [xchina.co](https://xchina.co/) disappear when using xhua

![sshot-061](https://user-images.githubusercontent.com/47524544/190025796-4ccf118c-dce8-43c0-8adc-83c90a7718b7.jpg)
![sshot-062](https://user-images.githubusercontent.com/47524544/190025811-2d315e6e-15ca-44d3-89df-85d7255d4427.jpg)

**Comment by LARASPY** [comment]
Fixed.
